name: CI

on: [push, pull_request]

jobs:
  linux:
    name: "Linux Ubuntu 20.04 (GNU 9.3.0)"
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Configuring CMake files
        id: building-files
        run: |
          mkdir build && cd build && cmake ..
      - name: Building library
        id: building-lib
        run: |
          cd build && cmake --build . --config Debug --target application -j 10 --
      - name: Cleanup
        id: clean-up
        run: |
          rm -r build

  windows:
    name: "Windows 10 (MSVC 19.29)"
    runs-on: windows-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Configuring CMake files
        id: building-files
        run: |
          mkdir build
          cd build
          cmake ..
      - name: Building library
        id: building-lib
        run: |
          cd build
          cmake --build . --config Debug --target glfw application -j 10 --
      - name: Cleanup
        id: clean-up
        run: |
          rm -r build

  macos:
    name: "macOS Catalina 10.15 (AppleClang 12.0)"
    runs-on: macos-latest
    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v2
      - name: Configuring CMake files
        id: building-files
        run: |
          mkdir build && cd build && cmake ..
      - name: Building library
        id: building-lib
        run: |
          cd build && cmake --build . --config Debug --target application -j 10 --
      - name: Cleanup
        id: clean-up
        run: |
          rm -r build
